services:
  redis:
    image: redis:latest
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks: [app]

  db:
    image: postgres:16.9
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [app]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["sh", "-lc", "uv run alembic upgrade head && uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"]
    networks: [app]

  arq-worker:
    build: ./backend
    restart: unless-stopped
    command: ["uv", "run", "arq", "src.core.arq_worker.WorkerSettings"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    env_file:
      - .env.docker
    networks: [app]
    volumes:
      - ./backend:/app
  
networks:
  app:

volumes:
  postgres_data:
  redis-data: