"""Update backend 0.2

Revision ID: 67de476d77bd
Revises: ba538a0596a9
Create Date: 2025-11-02 13:45:34.697893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67de476d77bd'
down_revision: Union[str, Sequence[str], None] = 'ba538a0596a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None: 
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Thêm column detailed_review với default value để tránh lỗi NOT NULL trên existing rows
    # Bước 1: Thêm column nullable với default value
    op.add_column('lawyer_rating', sa.Column('detailed_review', sa.Text(), nullable=True, server_default=sa.text("''")))
    
    # Bước 2: Update existing rows (nếu có) để set detailed_review=''
    op.execute("UPDATE lawyer_rating SET detailed_review = '' WHERE detailed_review IS NULL")
    
    # Bước 3: Set column thành NOT NULL
    op.alter_column('lawyer_rating', 'detailed_review',
                    existing_type=sa.Text(),
                    nullable=False,
                    server_default=sa.text("''"))
    
    # Thêm column expired với default value để tránh lỗi NOT NULL trên existing rows
    # Bước 1: Thêm column nullable với default value
    op.add_column('lawyer_schedule_slot', sa.Column('expired', sa.Boolean(), nullable=True, server_default=sa.text('false')))
    
    # Bước 2: Update existing rows (nếu có) để set expired=False
    op.execute("UPDATE lawyer_schedule_slot SET expired = false WHERE expired IS NULL")
    
    # Bước 3: Set column thành NOT NULL
    op.alter_column('lawyer_schedule_slot', 'expired',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyer_schedule_slot', 'expired')
    op.drop_column('lawyer_rating', 'detailed_review')
    # ### end Alembic commands ###
