"""Update backend 0.2

Revision ID: 67de476d77bd
Revises: ba538a0596a9
Create Date: 2025-11-02 13:45:34.697893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67de476d77bd'
down_revision: Union[str, Sequence[str], None] = 'ba538a0596a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer_rating', sa.Column('detailed_review', sa.Text(), nullable=False))
    op.add_column('lawyer_schedule_slot', sa.Column('expired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyer_schedule_slot', 'expired')
    op.drop_column('lawyer_rating', 'detailed_review')
    # ### end Alembic commands ###
