"""3rd

Revision ID: 6836d740a452
Revises: 67de476d77bd
Create Date: 2025-11-02 19:42:43.565873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6836d740a452'
down_revision: Union[str, Sequence[str], None] = '67de476d77bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lawyer_rating', 'detailed_review',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('lawyer_schedule_slot', 'expired')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer_schedule_slot', sa.Column('expired', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('lawyer_rating', 'detailed_review',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
